apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deployment
  labels:
    app: mongo
spec:  #Deployment specific configuration
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template: #template: configuration for Pod; Blueprint for Pods
    metadata:
      labels:
        app: mongo
    spec:
      containers:  #We can have multiple containers per pod; But best practice one main application per pod
      - name: mongodb   #Name that we give; can be any name
        image: mongo:5.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-user
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: mongo-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017